Fix: node image building
The error we got was:

```
  [...]
+++ [0918 20:17:42] Deleting docker image k8s.gcr.io/kube-proxy-amd64:v1.18.10-rc.0.3_c4832b4a9ab9f4
+++ [0918 20:17:42] Docker builds done
Failed to build Kubernetes: command "sh -c 'cd go/src/k8s.io/kubernetes && hack/print-workspace-status.sh'" failed with error: exit status 2
ERROR: error building node image: failed to build kubernetes: command "sh -c 'cd go/src/k8s.io/kubernetes && hack/print-workspace-status.sh'" failed with error: exit status 2
Command Output: sh: 1: cd: can't cd to go/src/k8s.io/kubernetes
```

The assumption is that this is due to the different monunts we have in
the build directory and a recent change in k/k build system:

```
/dev/sdb on /tmp/build/e55deab7 type ext4 (rw,relatime)
/dev/sdb on /tmp/build/e55deab7/exported-node-image type ext4 (rw,relatime)
/dev/sdb on /tmp/build/e55deab7/exported-node-rootfs type ext4 (rw,relatime)
/dev/sdb on /tmp/build/e55deab7/go/src/k8s.io/kubernetes type ext4 (rw,relatime)
/dev/sdb on /tmp/build/e55deab7/kind-on-c type ext4 (rw,relatime)
/dev/sdb on /tmp/build/e55deab7/kind-release type ext4 (rw,relatime)
/dev/sdb on /tmp/build/e55deab7/outputs type ext4 (rw,relatime)
```

Dropping into the GOPATH directly and building the image from there
seems to work, building from the build directory seems to break some
path discovery in k/k's build scripts.